version: "3.8"
services:
 cardoc-prod-db:
    container_name: cardoc-prod-db
    image: postgres:14-alpine
    restart: always
    command: postgres -c listen_addresses='*'
    volumes:
      - ./db_data/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --auth-host=scram-sha-256
      - TZ="Asia/Seoul"
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME} 
      - POSTGRES_USER=${DB_USERNAME}
    expose:
      - 5432
 cardoc-prod-app:
    container_name: cardoc-prod-app
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    restart: always
    volumes:
      - appdata:/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - cardoc-prod-db
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh cardoc-prod-db:${DB_PORT} -t 15
        npm run migration:run
        npm run start
volumes:
  appdata:
    driver: local