 cardoc-dev-db:
    container_name: cardoc-dev-db
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --auth-host=scram-sha-256
      - TZ="Asia/Seoul"
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cardoc_dev