version: "3.8"
services:
  cardoc-dev-db:
    container_name: cardoc-dev-db
    image: postgres:14-alpine
    restart: always
    command: postgres -c listen_addresses='*'
    volumes:
      - ./db_data/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --auth-host=scram-sha-256
      - TZ="Asia/Seoul"
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
    ports:
      - 5432:5432
    expose:
      - 5432
