server:
  port: 3000

db:
  host: 'localhost'
  type: 'postgres'
  username: 'postgres'
  password: 'postgres'
  database: 'cardoc_dev'
  synchronize: true
  port: 5432

jwt:
  secret: 'secret'
  expiresIn: 3600
